name: action_figures_app
description: Demo ingreso y listado de figuras de acciÃ³n con foto y API Flask
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  image_picker: ^1.0.5
  path: ^1.8.3
  image: ^4.1.7
  geolocator: ^10.1.0
  flutter_secure_storage: ^9.0.0
  screen_protector: ^1.3.0
  dio: ^5.4.0
  local_auth: ^2.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
